name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    
    - name: Install dependencies
      run: |
        poetry install
    
    - name: Run linters
      continue-on-error: true
      run: |
        poetry run black . --check
        poetry run flake8 .
        poetry run isort . --check
    
    - name: Run tests
      continue-on-error: true
      run: |
        poetry run pytest
    
    - name: Download ffmpeg
      run: |
        Invoke-WebRequest -Uri "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip" -OutFile "ffmpeg.zip"
        Expand-Archive -Path "ffmpeg.zip" -DestinationPath "ffmpeg"
        Copy-Item "ffmpeg/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe" "ffmpeg.exe"
        Copy-Item "ffmpeg/ffmpeg-master-latest-win64-gpl/bin/ffprobe.exe" "ffprobe.exe"

    - name: Build executable
      run: |
        poetry run pyinstaller --name=vidleech --onefile --noconsole --clean --version-file="version_info.txt" --add-data "src/resources;src/resources" --add-binary "ffmpeg.exe;." --add-binary "ffprobe.exe;." --paths "." src/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vidleech-windows
        path: dist/vidleech.exe
        
    - name: Get version from pyproject.toml
      id: get_version
      run: |
        $version = (Get-Content pyproject.toml | Select-String -Pattern 'version = "([^"]+)"').Matches.Groups[1].Value
        echo "version=$version" >> $env:GITHUB_OUTPUT
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
        files: |
          dist/vidleech.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
