name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install Poetry
      run: |
        (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
    
    - name: Install dependencies
      run: poetry install
    
    - name: Build executable
      run: |
        poetry run pyinstaller --name=vidleech --onefile --noconsole --clean --add-data "src/resources;resources" src/main.py
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/vidleech.exe
        name: Release ${{ github.ref_name }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
